# Generated by Django 4.2.1 on 2023-07-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='dateOfPosting',
            field=models.CharField(max_length=10),
        ),
    ]
