# Generated by Django 4.2.1 on 2023-07-06 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0003_alter_jobpost_dateofposting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='dateOfPosting',
        ),
    ]
