# Generated by Django 4.2.1 on 2023-07-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0004_remove_jobpost_dateofposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='jobPostingDate',
            field=models.DateField(default=None, null=True),
        ),
    ]
